### ISSUE TITLE
feat(workspace): Add `rustfmt.toml`

### ISSUE THREAD

**Issue by clabby** [ethereum-optimism/kona#72]
## Overview

Once it won't require large PRs to have painful rebases, we should establish a `rustfmt.toml`.

Taken from `reth`, which is one I like the style of:

```toml
reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 100
wrap_comments = true
binop_separator = "Back"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
```
